# Generated by Django 5.1.7 on 2025-03-26 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Código de identificación único del producto', max_length=16, unique=True, verbose_name='Código (SKU)')),
                ('name', models.CharField(help_text='Nombre del producto', max_length=64, verbose_name='Nombre')),
                ('description', models.TextField(help_text='Descripción corta del producto', max_length=256, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio unitario del producto', max_digits=8, verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad disponible del producto', verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaser', models.CharField(help_text='Nombre del comprador', max_length=64, verbose_name='Comprador')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, help_text='Costo de envío para este producto en la orden', max_digits=8, verbose_name='Costo de envío')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal del costo del pedido', max_digits=10, verbose_name='Subtotal')),
                ('discount', models.DecimalField(decimal_places=2, help_text='Suma total del descuento aplicado al pedido', max_digits=10, verbose_name='Descuento')),
                ('iva', models.DecimalField(decimal_places=2, default=16.0, help_text='Suma total de impuestos aplicados al pedido', max_digits=4, verbose_name='Impuestos (IVA %)')),
                ('total', models.DecimalField(decimal_places=2, help_text='Costo total del pedido', max_digits=10, verbose_name='Total')),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Procesando', 'Procesando'), ('Procesando', 'Procesando'), ('Cancelada', 'Cancelada')], default='Pendiente', help_text='Estado actual de la orden', max_length=32, verbose_name='Estado')),
                ('order_date', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se realizó el pedido', verbose_name='Fecha de pedido')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre único del proveedor', max_length=64, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(help_text='Descripción del proveedor', max_length=256, verbose_name='Descripción')),
                ('shipping', models.DecimalField(decimal_places=2, help_text='Coste de envío por orden de compra', max_digits=10, verbose_name='Envío')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Número de unidades solicitadas del producto', verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio por unidad del producto en esta orden', max_digits=8, verbose_name='Precio unitario')),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento aplicado al producto en esta orden', max_digits=5, verbose_name='Descuento aplicado (%)')),
                ('product', models.ForeignKey(help_text='Producto solicitado en la orden de compra', null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.product', verbose_name='Producto')),
                ('purchase_order', models.ForeignKey(help_text='Orden a la que pertenece este producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='API.purchaseorder', verbose_name='Orden de compra')),
                ('supplier', models.ForeignKey(help_text='Proveedor del producto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Ítem de Orden',
                'verbose_name_plural': 'Ítems de Orden',
            },
        ),
        migrations.CreateModel(
            name='SupplierProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum', models.PositiveIntegerField(default=0, help_text='Cantidad mínima del mismo producto necesaria para aplicar el descuento', verbose_name='Cantidad mínima')),
                ('discount', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento a aplicar al producto', max_digits=4, verbose_name='Descuento')),
                ('product', models.ForeignKey(help_text='Producto al que se aplica el descuento', on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='API.product', verbose_name='Producto')),
                ('supplier', models.ForeignKey(help_text='Proveedor que aplica el descuento', on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='API.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
                'unique_together': {('supplier', 'product', 'minimum')},
            },
        ),
    ]
