# Generated by Django 5.1.7 on 2025-03-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Slug del producto', null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Slug del proveedor', null=True, verbose_name='Slug'),
        ),
    ]
