# Generated by Django 5.1.7 on 2025-03-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_product_slug_supplier_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplierproducts',
            unique_together={('supplier', 'product')},
        ),
        migrations.AddField(
            model_name='supplierproducts',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Slug del producto proveedor', null=True, verbose_name='Slug'),
        ),
    ]
