# Generated by Django 5.1.7 on 2025-04-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_supplierproducts_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierproducts',
            options={'verbose_name': 'Producto por proveedor', 'verbose_name_plural': 'Productos por proveedor'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='discount_applied',
        ),
        migrations.RemoveField(
            model_name='supplierproducts',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='supplierproducts',
            name='minimum',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ieps',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma total de impuestos por IEPS aplicados al pedido', max_digits=4, verbose_name='Impuestos (IEPS %)'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='ieps',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de impuestos por IEPS aplicados al producto', max_digits=4, verbose_name='Impuestos (IEPS %)'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de impuestos aplicados al producto', max_digits=4, verbose_name='Impuestos (IVA %)'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Importe total del producto', max_digits=8, verbose_name='Importe'),
        ),
        migrations.AddField(
            model_name='supplierproducts',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo unitario del producto', max_digits=8, verbose_name='Costo'),
        ),
        migrations.AddField(
            model_name='supplierproducts',
            name='ieps',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de impuestos por IEPS aplicados al producto', max_digits=4, verbose_name='Impuestos (IEPS %)'),
        ),
        migrations.AddField(
            model_name='supplierproducts',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de impuestos aplicados al producto', max_digits=4, verbose_name='Impuestos (IVA %)'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma total de impuestos aplicados al pedido', max_digits=4, verbose_name='Impuestos (IVA %)'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo total del pedido', max_digits=10, verbose_name='Total'),
        ),
    ]
