# Generated by Django 5.1.7 on 2025-04-01 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_supplierproducts_options_remove_product_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierproducts',
            old_name='cost',
            new_name='product_cost',
        ),
        migrations.RenameField(
            model_name='supplierproducts',
            old_name='ieps',
            new_name='product_ieps',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='ieps',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='supplierproducts',
            name='iva',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ieps_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma del IEPS de los productos', max_digits=10, verbose_name='IEPS (total)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='iva_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma del IVA de los productos', max_digits=10, verbose_name='IVA (total)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Slug de la orden de compra', null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo estándar por envío de mercancía', max_digits=10, verbose_name='Tarifa de envío'),
        ),
        migrations.AddField(
            model_name='supplierproducts',
            name='product_iva',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de impuestos base aplicados al producto', max_digits=4, verbose_name='Impuestos (IVA %)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='Código del producto', max_length=16, unique=True, verbose_name='Código (SKU)'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha en que se realizó la orden de compra', verbose_name='Fecha de orden'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchaser',
            field=models.ForeignKey(help_text='Usuario que realiza la orden de compra', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Comprador'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo total de envío', max_digits=10, verbose_name='Costo de envío'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma del precio unitario de los productos', max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma total del costo de la orden', max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='supplierproducts',
            name='product',
            field=models.ForeignKey(help_text='Producto ofrecido por el proveedor', on_delete=django.db.models.deletion.PROTECT, to='API.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='supplierproducts',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Slug del producto ofrecido por el proveedor', null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='supplierproducts',
            name='supplier',
            field=models.ForeignKey(help_text='Proveedor de productos', on_delete=django.db.models.deletion.PROTECT, to='API.supplier', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Cantidad pedida del mismo producto', verbose_name='Cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Costo unitario del producto', max_digits=8, verbose_name='Costo')),
                ('iva', models.DecimalField(decimal_places=2, help_text='Porcentaje de IVA aplicado al producto', max_digits=4, verbose_name='IVA (%)')),
                ('ieps', models.DecimalField(decimal_places=2, help_text='Porcentaje de IEPS aplicado al producto', max_digits=4, verbose_name='IEPS (%)')),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Importe total del producto', max_digits=8, verbose_name='Importe')),
                ('slug', models.SlugField(blank=True, default='', help_text='Slug del producto en la orden de compra', null=True, verbose_name='Slug')),
                ('product', models.ForeignKey(help_text='Producto a incluir', on_delete=django.db.models.deletion.PROTECT, to='API.product', verbose_name='Producto')),
                ('purchase_order', models.ForeignKey(help_text='Orden de compra en la cual se incluirá el producto', on_delete=django.db.models.deletion.CASCADE, to='API.purchaseorder', verbose_name='Orden de compra')),
                ('supplier', models.ForeignKey(help_text='Proveedor del producto', on_delete=django.db.models.deletion.PROTECT, to='API.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Producto (Orden de Compra)',
                'verbose_name_plural': 'Productos (Órdenes de Compra)',
                'unique_together': {('purchase_order', 'product', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, help_text='Costo de envío dado por el proveedor', max_digits=10, verbose_name='Costo de envío')),
                ('slug', models.SlugField(blank=True, default='', help_text='Slug del costo de envío en la orden de compra', null=True, verbose_name='Slug')),
                ('purchase_order', models.ForeignKey(help_text='Orden de compra a la que pertenece el envío', on_delete=django.db.models.deletion.CASCADE, to='API.purchaseorder', verbose_name='Orden de compra')),
                ('supplier', models.ForeignKey(help_text='Proveedor que realiza el envío', on_delete=django.db.models.deletion.PROTECT, to='API.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Costo de Envío (Orden de Compra)',
                'verbose_name_plural': 'Costos de Envío (Órdenes de Compra)',
                'unique_together': {('purchase_order', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del almacén', max_length=64, verbose_name='Nombre')),
                ('description', models.TextField(help_text='Descripción del almacén', max_length=256, verbose_name='Descripción')),
                ('slug', models.SlugField(blank=True, default='', help_text='Slug del almacén', null=True, verbose_name='Slug')),
                ('owner', models.ForeignKey(help_text='Propietario del almacén', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
            },
        ),
        migrations.CreateModel(
            name='WarehouseProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_state', models.BooleanField(default=True, help_text='Estado del producto (True=Activo, False=Inactivo)', verbose_name='Estado')),
                ('product_stock', models.PositiveIntegerField(default=0, help_text='Stock disponible del producto', verbose_name='Stock')),
                ('slug', models.SlugField(blank=True, default='', help_text='Slug del producto almacenado', null=True, verbose_name='Slug')),
                ('product', models.ForeignKey(help_text='Producto a almacenar', on_delete=django.db.models.deletion.PROTECT, to='API.product', verbose_name='Producto')),
                ('warehouse', models.ForeignKey(help_text='Almacén en el que se tendrá el producto', on_delete=django.db.models.deletion.PROTECT, to='API.warehouse', verbose_name='Almacén')),
            ],
            options={
                'verbose_name': 'Producto almacenado',
                'verbose_name_plural': 'Productos almacenados',
                'unique_together': {('warehouse', 'product')},
            },
        ),
        migrations.DeleteModel(
            name='PurchaseOrderItem',
        ),
    ]
