# Generated by Django 5.1.7 on 2025-04-01 22:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_rename_cost_supplierproducts_product_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': 'Orden de compra', 'verbose_name_plural': 'Órdenes de compra'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderproducts',
            options={'verbose_name': 'Producto (OC-R)', 'verbose_name_plural': 'Productos (OC-R)'},
        ),
        migrations.AlterModelOptions(
            name='purchaseordershipping',
            options={'verbose_name': 'Costo de envío (OC-R)', 'verbose_name_plural': 'Costos de envío (OC-R)'},
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('owner', 'name')},
        ),
    ]
