# Generated by Django 5.1.7 on 2025-04-07 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_purchaseorder_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseorderproducts',
            unique_together={('purchase_order', 'product')},
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo unitario del producto', max_digits=8, verbose_name='Costo'),
        ),
        migrations.AddField(
            model_name='product',
            name='ieps',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de IEPS del producto', max_digits=4, verbose_name='Impuestos (IEPS %)'),
        ),
        migrations.AddField(
            model_name='product',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de IVA del producto', max_digits=4, verbose_name='Impuestos (IVA %)'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(default=1, help_text='Proveedor del producto', on_delete=django.db.models.deletion.PROTECT, to='API.supplier', verbose_name='Proveedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha en que se realiza la orden de compra', verbose_name='Fecha de orden'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma total de costos de envío', max_digits=10, verbose_name='Costo de envío'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo total de la orden de compra', max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='purchaseorderproducts',
            name='ieps',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de IEPS del producto', max_digits=4, verbose_name='IEPS (%)'),
        ),
        migrations.AlterField(
            model_name='purchaseorderproducts',
            name='iva',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de IVA del producto', max_digits=4, verbose_name='IVA (%)'),
        ),
        migrations.AlterField(
            model_name='purchaseorderproducts',
            name='purchase_order',
            field=models.ForeignKey(help_text='Orden de compra del producto', on_delete=django.db.models.deletion.CASCADE, to='API.purchaseorder', verbose_name='Orden de compra'),
        ),
        migrations.AlterField(
            model_name='purchaseorderproducts',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad pedida', verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='purchaseordershipping',
            name='purchase_order',
            field=models.ForeignKey(help_text='Orden de compra del envío', on_delete=django.db.models.deletion.CASCADE, to='API.purchaseorder', verbose_name='Orden de compra'),
        ),
        migrations.AlterField(
            model_name='purchaseordershipping',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo total del envío', max_digits=10, verbose_name='Costo de envío'),
        ),
        migrations.AlterField(
            model_name='warehouseproducts',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Slug del producto a almacenar', null=True, verbose_name='Slug'),
        ),
        migrations.DeleteModel(
            name='SupplierProducts',
        ),
        migrations.RemoveField(
            model_name='purchaseorderproducts',
            name='supplier',
        ),
    ]
