# Generated by Django 5.1.7 on 2025-04-08 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_purchaseorderproducts_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 8, 0, 28, 33, 734253, tzinfo=datetime.timezone.utc), help_text='Fecha en que se realiza la orden de compra', null=True, verbose_name='Fecha de orden'),
        ),
    ]
