# Generated by Django 5.1.7 on 2025-04-08 00:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_purchaseorder_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Fecha en que se realiza la orden de compra', null=True, verbose_name='Fecha de orden'),
        ),
    ]
